In [29]:
import numpy as np

In [3]:
A = np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [4]:
np.array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [5]:
A.shape

(3, 3)

In [6]:
vector = np.array([1, 2, 3])

In [7]:
vector.shape

(3,)

In [8]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

untuk mengambil posisi kolom

In [9]:
A[1]
# mengambil array dari index 1 atau bisa ditulis A [:,1]

array([4, 5, 6])

In [10]:
A[:,-1]
# pengambilan array kolom terakhir

array([3, 6, 9])

In [11]:
np.diag(A)

array([1, 5, 9])

In [12]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [13]:
A @ np.eye(3)

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [14]:
np.zeros(3)

array([0., 0., 0.])

In [15]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

Operasi Aritmatika

In [16]:
B = np.array([[3, 1, 1],
              [2, 1, 2],
              [2, 0, 0]])
B

array([[3, 1, 1],
       [2, 1, 2],
       [2, 0, 0]])

In [17]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [18]:
A + 10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [19]:
A + B

array([[4, 3, 4],
       [6, 6, 8],
       [9, 8, 9]])

In [20]:
10 - A

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [21]:
B - A

array([[ 2, -1, -2],
       [-2, -4, -4],
       [-5, -8, -9]])

In [22]:
A + vector

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [23]:
C = np.array([[0, 0, 4],
             [1, 4, 2]])

C

array([[0, 0, 4],
       [1, 4, 2]])

In [24]:
A + C

ValueError: operands could not be broadcast together with shapes (3,3) (2,3) 

Contoh hadamard product: perkalian atau pembagian biasa

In [ ]:
A / 2

array([[0.5, 1. , 1.5],
       [2. , 2.5, 3. ],
       [3.5, 4. , 4.5]])

In [ ]:
A / B

C:\Users\MyLenovo\AppData\Local\Temp\ipykernel_10140\3006334257.py:1: RuntimeWarning: divide by zero encountered in true_divide
  A / B


array([[0.33333333, 2.        , 3.        ],
       [2.        , 5.        , 3.        ],
       [3.5       ,        inf,        inf]])

matrix matrix multiplication atau Dot

In [ ]:
A1 = np.array([[1, 2],
              [0, 3],
              [3, 1],
              [1, 1]])

In [ ]:
A1

array([[1, 2],
       [0, 3],
       [3, 1],
       [1, 1]])

In [ ]:
B1 = np.array([[1, 2, 2],
              [0, 3, 1]])

In [ ]:
B1

array([[1, 2, 2],
       [0, 3, 1]])

In [ ]:
A1 @ B1
# [1x1 + 2x0 1x2 + 2x3 1x2 + 2x1]
# [0x1 + 3x0 0x2 + 3x3 0x2 + 3x1]
# [3x1 + 1x0 3x2 + 1x3 3x2 + 1x1]
# [1x1 + 1x0 1x2 + 1x3 1x2 + 1x1]

array([[1, 8, 4],
       [0, 9, 3],
       [3, 9, 7],
       [1, 5, 3]])

In [ ]:
A(m,k) @ B(k,n) = C(m, n)
A(4,2) @ B(2,3) = C(4, 3)
rumus = a1,1 x b1,1 + a1,2 x b1,2 

Transpose

In [ ]:
C = np.array([[1, 2, 2],
              [0, 3, 1]])

In [ ]:
C.T

array([[1, 0],
       [2, 3],
       [2, 1]])

In [ ]:
C

array([[1, 2, 2],
       [0, 3, 1]])

Inverse

In [ ]:
B_inv = np.linalg.inv(B)

In [ ]:
S = np.array([[1, 2, 2],
              [2, 4, 4],
              [2, 3, 4]])

In [ ]:
np.linalg.inv(S)

LinAlgError: Singular matrix

rumus inverse 2 kolom x 2 baris = A pangkat -1 (2,2) = 1 / determinan A (d, -b) (-c a)
jika matrix mempunyai nilai determinan = 0 , matrix tersebut tidak memiliki inverse
a = [2, 1] [2, 8], det = (2 x 8) - (2 x 1) = 16 - 2 = 14 <- jika 0 tidak memiliki inverse
inverse = 1/det * [8 , 2][-1, -2] = [8/14 , 1/7] [ -1/14 , -1/7]

Tensor

In [26]:
S1 = np.array([[1, 1, 2],
              [2, 1, 2]])

S2 = np.array([[0, 2, 3],
              [3, 4, 7]])

S3 = np.array([[2, 3, 5],
              [4, 6, 6]])

S4 = np.array([[3, 2, 2],
              [1, 2, 4]])

In [27]:
tensor = np.array([S1, S2, S3, S4])
tensor

array([[[1, 1, 2],
        [2, 1, 2]],

       [[0, 2, 3],
        [3, 4, 7]],

       [[2, 3, 5],
        [4, 6, 6]],

       [[3, 2, 2],
        [1, 2, 4]]])

In [28]:
tensor.shape

(4, 2, 3)

In [38]:
S1 = np.array([[23, 50],
              [7, 12]]

S2 = np.array([57, 67],
              [99, 43])

S3 = np.array([75, 21],
              [57, 12])

S4 = np.array([87, 26],
              [18, 84])

TypeError: Field elements must be 2- or 3-tuples, got '7'

In [33]:
tensor

array([[[[23, 50,  7, 12],
         [57, 67, 99, 43],
         [75, 21, 57, 12],
         [87, 26, 18, 84]]]])

In [49]:
S1 = np.array([[[[23, 50],
              [7, 12]]]])

S2 = np.array([[[[57, 67],
              [99, 43]]]])

S3 = np.array([[[[75, 21],
              [57, 21]]]])

S4 = np.array([[[[87, 26],
              [18, 84]]]])

In [50]:
tensor = np.array([S1, S2, S3, S4])
tensor

array([[[[[23, 50],
          [ 7, 12]]]],



       [[[[57, 67],
          [99, 43]]]],



       [[[[75, 21],
          [57, 21]]]],



       [[[[87, 26],
          [18, 84]]]]])

In [19]:
tensor.shape

(4, 2, 2)

In [44]:
x = np.zeros((4,4,4))
x[:,None]

array([[[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]],


       [[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]]])